apiVersion: pdai.pdai.io/v1alpha1
kind: PDEngineProfile
metadata:
  labels:
    app.kubernetes.io/name: pd-manager
    app.kubernetes.io/managed-by: kustomize
  name: pdengineprofile-sample
spec:
  # TODO(user): Add fields here
