//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicabilitySpec) DeepCopyInto(out *ApplicabilitySpec) {
	*out = *in
	if in.GPUTypes != nil {
		in, out := &in.GPUTypes, &out.GPUTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinGPUMemoryGiB != nil {
		in, out := &in.MinGPUMemoryGiB, &out.MinGPUMemoryGiB
		*out = new(int32)
		**out = **in
	}
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.ModelSizeRange != nil {
		in, out := &in.ModelSizeRange, &out.ModelSizeRange
		*out = new(ModelSizeRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicabilitySpec.
func (in *ApplicabilitySpec) DeepCopy() *ApplicabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ApplicabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngineConfig) DeepCopyInto(out *EngineConfig) {
	*out = *in
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.KVTransfer != nil {
		in, out := &in.KVTransfer, &out.KVTransfer
		*out = new(KVTransfer)
		**out = **in
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = new(RoleExtraArgs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngineConfig.
func (in *EngineConfig) DeepCopy() *EngineConfig {
	if in == nil {
		return nil
	}
	out := new(EngineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngineRuntime) DeepCopyInto(out *EngineRuntime) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]RuntimeContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngineRuntime.
func (in *EngineRuntime) DeepCopy() *EngineRuntime {
	if in == nil {
		return nil
	}
	out := new(EngineRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventRecord) DeepCopyInto(out *EventRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventRecord.
func (in *EventRecord) DeepCopy() *EventRecord {
	if in == nil {
		return nil
	}
	out := new(EventRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPASpec) DeepCopyInto(out *HPASpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPASpec.
func (in *HPASpec) DeepCopy() *HPASpec {
	if in == nil {
		return nil
	}
	out := new(HPASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVTransfer) DeepCopyInto(out *KVTransfer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVTransfer.
func (in *KVTransfer) DeepCopy() *KVTransfer {
	if in == nil {
		return nil
	}
	out := new(KVTransfer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSizeRange) DeepCopyInto(out *ModelSizeRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSizeRange.
func (in *ModelSizeRange) DeepCopy() *ModelSizeRange {
	if in == nil {
		return nil
	}
	out := new(ModelSizeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStorageSpec) DeepCopyInto(out *ModelStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStorageSpec.
func (in *ModelStorageSpec) DeepCopy() *ModelStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ModelStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDEngineProfile) DeepCopyInto(out *PDEngineProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDEngineProfile.
func (in *PDEngineProfile) DeepCopy() *PDEngineProfile {
	if in == nil {
		return nil
	}
	out := new(PDEngineProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDEngineProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDEngineProfileList) DeepCopyInto(out *PDEngineProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PDEngineProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDEngineProfileList.
func (in *PDEngineProfileList) DeepCopy() *PDEngineProfileList {
	if in == nil {
		return nil
	}
	out := new(PDEngineProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDEngineProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDEngineProfileSpec) DeepCopyInto(out *PDEngineProfileSpec) {
	*out = *in
	if in.Applicability != nil {
		in, out := &in.Applicability, &out.Applicability
		*out = new(ApplicabilitySpec)
		(*in).DeepCopyInto(*out)
	}
	out.Images = in.Images
	if in.EngineRuntimes != nil {
		in, out := &in.EngineRuntimes, &out.EngineRuntimes
		*out = new(RoleEngineRuntimes)
		(*in).DeepCopyInto(*out)
	}
	in.EngineConfig.DeepCopyInto(&out.EngineConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDEngineProfileSpec.
func (in *PDEngineProfileSpec) DeepCopy() *PDEngineProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PDEngineProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDEngineProfileStatus) DeepCopyInto(out *PDEngineProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDEngineProfileStatus.
func (in *PDEngineProfileStatus) DeepCopy() *PDEngineProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PDEngineProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDInferenceService) DeepCopyInto(out *PDInferenceService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDInferenceService.
func (in *PDInferenceService) DeepCopy() *PDInferenceService {
	if in == nil {
		return nil
	}
	out := new(PDInferenceService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDInferenceService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDInferenceServiceList) DeepCopyInto(out *PDInferenceServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PDInferenceService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDInferenceServiceList.
func (in *PDInferenceServiceList) DeepCopy() *PDInferenceServiceList {
	if in == nil {
		return nil
	}
	out := new(PDInferenceServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDInferenceServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDInferenceServiceSpec) DeepCopyInto(out *PDInferenceServiceSpec) {
	*out = *in
	out.ModelStorage = in.ModelStorage
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(RoleImages)
		**out = **in
	}
	out.Prefill = in.Prefill
	out.Decode = in.Decode
	if in.Router != nil {
		in, out := &in.Router, &out.Router
		*out = new(RouterSpec)
		**out = **in
	}
	if in.EngineConfig != nil {
		in, out := &in.EngineConfig, &out.EngineConfig
		*out = new(EngineConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(ScalingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDInferenceServiceSpec.
func (in *PDInferenceServiceSpec) DeepCopy() *PDInferenceServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PDInferenceServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDInferenceServiceStatus) DeepCopyInto(out *PDInferenceServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoleStatuses != nil {
		in, out := &in.RoleStatuses, &out.RoleStatuses
		*out = make([]RoleStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastEvent != nil {
		in, out := &in.LastEvent, &out.LastEvent
		*out = new(EventRecord)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDInferenceServiceStatus.
func (in *PDInferenceServiceStatus) DeepCopy() *PDInferenceServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PDInferenceServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleEngineRuntimes) DeepCopyInto(out *RoleEngineRuntimes) {
	*out = *in
	if in.Prefill != nil {
		in, out := &in.Prefill, &out.Prefill
		*out = make([]EngineRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Decode != nil {
		in, out := &in.Decode, &out.Decode
		*out = make([]EngineRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = make([]EngineRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleEngineRuntimes.
func (in *RoleEngineRuntimes) DeepCopy() *RoleEngineRuntimes {
	if in == nil {
		return nil
	}
	out := new(RoleEngineRuntimes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleExtraArgs) DeepCopyInto(out *RoleExtraArgs) {
	*out = *in
	if in.Prefill != nil {
		in, out := &in.Prefill, &out.Prefill
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Decode != nil {
		in, out := &in.Decode, &out.Decode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleExtraArgs.
func (in *RoleExtraArgs) DeepCopy() *RoleExtraArgs {
	if in == nil {
		return nil
	}
	out := new(RoleExtraArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleImages) DeepCopyInto(out *RoleImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleImages.
func (in *RoleImages) DeepCopy() *RoleImages {
	if in == nil {
		return nil
	}
	out := new(RoleImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleSpec) DeepCopyInto(out *RoleSpec) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleSpec.
func (in *RoleSpec) DeepCopy() *RoleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleStatus) DeepCopyInto(out *RoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatus.
func (in *RoleStatus) DeepCopy() *RoleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterSpec) DeepCopyInto(out *RouterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterSpec.
func (in *RouterSpec) DeepCopy() *RouterSpec {
	if in == nil {
		return nil
	}
	out := new(RouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeContainer) DeepCopyInto(out *RuntimeContainer) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeContainer.
func (in *RuntimeContainer) DeepCopy() *RuntimeContainer {
	if in == nil {
		return nil
	}
	out := new(RuntimeContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
	if in.Decode != nil {
		in, out := &in.Decode, &out.Decode
		*out = new(HPASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Prefill != nil {
		in, out := &in.Prefill, &out.Prefill
		*out = new(HPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSpec.
func (in *ScalingSpec) DeepCopy() *ScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingSpec)
	in.DeepCopyInto(out)
	return out
}
